### ISSUE TITLE
Check aritmethic operations

### ISSUE THREAD

**Issue by gamassimino** [gamassimino/compiler_project#26]
- [x] Plus
- [x] Times
- [x] Minus
- [x] Divide
- [x] Percentage
- [x] AddAssignment
- [x] SubAssignment

**Comment by gamassimino** [comment]
I'm not sure but I think that the `divide`& `percentage` operators works OK

**Comment by ezedepetris** [comment]
AddAssignment, SubAssignment done in this Rev [ee6a6e9 ]
