### ISSUE TITLE
Check booleans operators

### ISSUE THREAD

**Issue by gamassimino** [gamassimino/compiler_project#27]
- [x] Check **greater**
- [x] Check **greater or equal**
- [x] Check **less**
- [x] Check **less or equal**
- [x] Check **and**
- [x] Check **or**
- [x] Check **not**

**Comment by ezedepetris** [comment]
All boolean's operators have been tested in simple form
cond1 = true
cond2 = false
num1 = 2
num2 = 2

cond1 || cond2
!cond2
cond1 && cond2
num1 <= num2
num1 >= num2
num1 < num2
num1 > num2

(cond1 || cond2) && (cond1 || cond2)
cond1 && (cond1 || cond2)
cond2 && (cond1 || cond2)

Rev -> [56f361d]
