### ISSUE TITLE
Test refactor + Documentation 

### ISSUE THREAD

**Issue by ezedepetris** [gamassimino/compiler_project#7]
- [x] Missing testing a program with several classes
- [x] Missing testing a program with a complex method
- [x] Missing comment the goal of each test
- [x] Make new test for detected syntactic and lexical errors
- [x] Make two script for test, one for success test an the other for failed test

**Comment by gamassimino** [comment]
@ezedepetris why dont we change this lines

```
"//" .* { System.out.println("COMMENT IN ONE LINE"); }
"/*"~"*/" { System.out.println("COMMENT IN SOMES LINE"); }
```

because is annoying when you run the test

**Comment by gamassimino** [comment]
part of this issue is in this commit 8de9877

**Comment by gamassimino** [comment]
this issue is donde 08c820d
